spring.application.name=ecommerce
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/dea2_user_service
spring.datasource.username=root
spring.datasource.password=kanivini

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=ChangeThisSecretToLongRandomString_AtLeast32Chars
app.jwt.expirationMs=86400000